# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: yarn
        
      - name: Run build
        run: build
        
      - name: Copy dist to Digital OCean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"

      # Instalar as dependencias do NPM/Yarn
      # Executar a build
      # Copiar pasta dist pra dentro da digital ocean
  
      # Substituir o código existente na pasta dist pelo novo código
      # Executar yarn na Digital Ocean
      # Executar as migrations do TypeOrm
        
      # Restart no servidor node

      - name: Run a one-line script
        run: echo Hello, world!
